name: Test Build

on:
  workflow_dispatch:
  push:
    branches:
      - ci-test

jobs:
  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          echo "---"
          git ls-files | head -20
          echo "---"
          ls -la android/ | head -10
